"""add composition_id to OrderItem

Revision ID: 1c5f5b67cf77
Revises: 37419a56ca6c
Create Date: 2026-03-21 10:26:28.490935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5f5b67cf77'
down_revision = '37419a56ca6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('composition_id', sa.Integer(), nullable=True))
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_orderitem_composition', 'composition', ['composition_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orderitem_composition', type_='foreignkey')
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('composition_id')

    # ### end Alembic commands ###
