"""add composition_image table

Revision ID: 4fd029ef5f64
Revises: 1c5f5b67cf77
Create Date: 2026-03-21 10:53:49.947806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd029ef5f64'
down_revision = '1c5f5b67cf77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composition_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('composition_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('preview_filename', sa.String(length=255), nullable=True),
    sa.Column('alt_text', sa.String(length=120), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['composition_id'], ['composition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('composition_image')
    # ### end Alembic commands ###
