"""add color_palette

Revision ID: 7190fe0abf3f
Revises: 4fd029ef5f64
Create Date: 2026-03-22 00:01:14.541762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7190fe0abf3f'
down_revision = '4fd029ef5f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_palette',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color_name', sa.String(length=64), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('price_modifier', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('color_palette')
    # ### end Alembic commands ###
