"""add delivery fields to order

Revision ID: 79e9a1a12e60
Revises: a7fd29d09725
Create Date: 2026-04-05 13:22:51.185750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e9a1a12e60'
down_revision = 'a7fd29d09725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('np_city_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('np_warehouse', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('np_warehouse')
        batch_op.drop_column('np_city_name')
        batch_op.drop_column('delivery_type')

    # ### end Alembic commands ###
