"""update Product and Color models

Revision ID: 7e76346c0851
Revises: c9a68151e958
Create Date: 2026-04-07 09:51:37.966821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e76346c0851'
down_revision = 'c9a68151e958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('color', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('color', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
