"""rename depth to length

Revision ID: cc905a73f429
Revises: 7190fe0abf3f
Create Date: 2026-03-23 13:14:45.566201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc905a73f429'
down_revision = '7190fe0abf3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', sa.Integer(), nullable=True))
        batch_op.drop_column('depth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depth', sa.INTEGER(), nullable=True))
        batch_op.drop_column('length')

    # ### end Alembic commands ###
