"""update models

Revision ID: d68b108ad15b
Revises: 7e76346c0851
Create Date: 2026-04-07 10:04:28.728974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68b108ad15b'
down_revision = '7e76346c0851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_order_number'), ['order_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_order_number'))
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
